name: docker-home

services:

  tailscale:
    image: tailscale/tailscale:latest
    container_name: docker-cont
    hostname: docker
    healthcheck:
      test: ["CMD", "test", "-f", "/central_storage/tailscale_docker_dns.txt"]
      interval: 15s
      timeout: 5s
      retries: 5
    environment:
      - TS_USERSPACE=false
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR=${CENTRAL_STORAGE_FOLDER}/tailscale_state
    volumes:
      - ${CENTRAL_STORAGE_FOLDER}/tailscale_state:/var/lib/tailscale
      - ${CENTRAL_STORAGE_FOLDER}:/central_storage
    devices:
      - /dev/net/tun:/dev/net/tun
    privileged: true
    cap_add: [NET_ADMIN]
    restart: on-failure
    command: >
      sh -c "
        apk add --no-cache jq
        tailscaled &
        sleep 10
        tailscale up --auth-key $${TS_AUTHKEY} --advertise-exit-node &
        tailscale status --json
        TAILSCALE_DNS=$$(tailscale status --json | jq -r '.Self.DNSName')
        TAILSCALE_DNS=$${TAILSCALE_DNS%.}
        echo "$${TAILSCALE_DNS}"
        echo "$${TAILSCALE_DNS}" > /central_storage/tailscale_docker_dns.txt
        echo 'DNS Name written to /central_storage/tailscale_docker_dns.txt'
        tail -f /dev/null
        "

  webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: webui
    restart: unless-stopped
    network_mode: service:tailscale
    environment:
      OLLAMA_BASE_URL: http://127.0.0.1:11434
    depends_on: [ ollama ]

  ollama:
    build:
      context: .
      dockerfile: ollama
    container_name: ollama
    restart: unless-stopped
    network_mode: service:tailscale
    volumes:
      - ${CENTRAL_STORAGE_FOLDER}/ollama-store:/root/.ollama 
    environment:
      OLLAMA_HOST: 127.0.0.1
      OLLAMA_PORT: 11434

  db:
    image: mariadb:10.6
    container_name: nextcloud-db
    command: >
      --transaction-isolation=READ-COMMITTED
      --log-bin=binlog
      --binlog-format=ROW
      --bind-address=127.0.0.1
    volumes:
      - ${SECURE_DATA_PATH}/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    restart: unless-stopped
    network_mode: service:tailscale

  nextcloud:
    image: nextcloud:31.0.4-apache
    container_name: nextcloud
    restart: unless-stopped
    depends_on:
      tailscale:
        condition: service_healthy
    volumes:
      - ${SECURE_DATA_PATH}/nextcloud:/var/www/html
      - ${CENTRAL_STORAGE_FOLDER}:/central_storage
      - ./nextcloud_trusted_domains.sh:/nextcloud_trusted_domains.sh
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=127.0.0.1
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
    entrypoint: ["/bin/bash", "/nextcloud_trusted_domains.sh"]  # Use the update script as entrypoint
    network_mode: service:tailscale